spring.config.import=optional:file:.env[.properties]

spring.application.name=TuniRate

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#JWT
jwt.secret=${JWT_SECRET}

#JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

#Uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#Pagination
spring.data.web.pageable.max-page-size=30

file.upload-dir=${FILE_UPLOAD_DIR}
file.base-url=${FILE_BASE_URL}

#Google authentication
google.client-id=${GOOGLE_CLIENT_ID}

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.multipart=TRACE

#Email
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0


# File output with rotation
logging.file.name=logs/tunirate.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.total-size-cap=100MB

# Only log YOUR code, silence framework noise
logging.level.root=WARN
logging.level.tn.anasazx.tunirate=DEBUG