spring.config.import=optional:file:.env[.properties]

spring.application.name=TuniRate


# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# JWT
jwt.secret=${JWT_SECRET}


# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false


# Uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.upload-dir=${UPLOAD_DIR:uploads}


# Pagination
spring.data.web.pageable.max-page-size=30