spring.config.import=optional:file:.env[.properties]

spring.application.name=TuniRate


# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# JWT
jwt.secret=${JWT_SECRET}


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# Pagination
spring.data.web.pageable.max-page-size=30


# for production
#file.upload-dir=/opt/tunirate/uploads
#file.base-url=http://37.187.32.120/uploads/

file.upload-dir=/Users/anasaz/tunirate/uploads
file.base-url=http://localhost:9000/uploads/
