name: Deploy TuniRate Backend

on:
  push:
    branches:
      - main


jobs:

  build:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'


      - name: Build Spring Boot
        run: |
          mvn clean package -DskipTests


      - name: Copy JAR to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ubuntu
          key: ${{ secrets.VPS_SSH_KEY }}
          source: target/*.jar
          target: /home/ubuntu/


      - name: Restart backend
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ubuntu
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo systemctl restart tunirate
            sudo systemctl status tunirate
